# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "The Startup Log"
email: "rbdundas@gmail.com"
description: "A blog for me to post the knowledge, notes and other miscellaneous information accumulated in various projects and activities."
baseurl: ""
url: "http://biskilicious.github.io"
twitter_username: "rbdundas"
github_username:  "biskilicious"

# Build settings
markdown: kramdown
permalink: /:categories/:title/